# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.kernelModules = [ "msr" "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [ "ntfs" ];


  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/6ae66ba6-6494-4a93-874c-147b37b63b27";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/324D-CB35"; # nixos drive
      fsType = "vfat";
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/91a1b476-4b73-4517-987c-8a82b2b5510b";
      fsType = "ext4";
    };


  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/56cb89b5-709b-44e9-9135-56dab4576414";
      fsType = "ext4";
    };

  fileSystems."/mnt/games" =
    {
      device = "/dev/disk/by-uuid/53ddb300-4589-48e6-a101-2d77091882e4";
      fsType = "ext4";
    };

  fileSystems."/mnt/windows" =
    {
      device = "/dev/disk/by-uuid/3AEA8E2CEA8DE50B";
      fsType = "ntfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    opengl = {
      enable = true;
      # driSupport = true;
      driSupport32Bit = true;
    };

    bluetooth.enable = true;
  };

  services.xserver.videoDrivers = [ "amdgpu" ];

  environment.systemPackages = with pkgs; [ gparted corectrl ];
}
